# These substitutions allow the end user to override certain values
substitutions:
  # Device Names
  name: "localbytes-plug-v2"
  friendly_name: "Localbytes Plug V2"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: localbytes.plug-pm-v2
    version: "0.2"

esp8266:
  board: esp01_1m

api:

ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://JamesSwift/localbytes-plug-pm-v2/localbytes-plug-pm-v2.yaml@main

wifi:
  ap:
    ssid: "${friendly_name}"

captive_portal:
